"""Shared, persona-independent game knowledge domain."""

from .contracts import (
    ClaimKind,
    ClaimStatus,
    DiscourseReferent,
    EvidenceLevel,
    KnowledgeNeed,
    KnowledgeNeedOutcome,
    KnowledgeObservation,
    KnowledgeResolverPort,
    KnowledgeScope,
    ObservationStatus,
    OriginClass,
    KnowledgeClaimCandidate,
    NegativeSearchSnapshot,
    ResolvedEntity,
    ResolvedTerm,
    RiskClass,
    SourceClass,
    SourceEvidence,
    TopicUnderstandingFrame,
    VersionReference,
    VersionSlot,
    canonical_source_url,
)
from .observation import (
    KnowledgeObservationService,
    KnowledgeOriginClassifier,
    OriginDecision,
)
from .resolver import KnowledgeEntityResolver
from .retrieval import (
    KnowledgeHit,
    KnowledgeNeedAssessor,
    KnowledgeRetriever,
)


__all__ = (
    "ClaimKind",
    "ClaimStatus",
    "DiscourseReferent",
    "EvidenceLevel",
    "KnowledgeNeed",
    "KnowledgeClaimCandidate",
    "KnowledgeNeedAssessor",
    "KnowledgeNeedOutcome",
    "KnowledgeObservation",
    "KnowledgeObservationService",
    "KnowledgeOriginClassifier",
    "KnowledgeEntityResolver",
    "KnowledgeHit",
    "KnowledgeRetriever",
    "KnowledgeResolverPort",
    "KnowledgeScope",
    "ObservationStatus",
    "OriginClass",
    "NegativeSearchSnapshot",
    "OriginDecision",
    "ResolvedEntity",
    "ResolvedTerm",
    "RiskClass",
    "SourceClass",
    "SourceEvidence",
    "TopicUnderstandingFrame",
    "VersionReference",
    "VersionSlot",
    "canonical_source_url",
)
